exclude: '^$'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks  # general
    rev: "v4.0.1"
    hooks:
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: requirements-txt-fixer
      - id: check-yaml
      - id: check-json
      - id: check-xml
      - id: check-merge-conflict
      - id: mixed-line-ending
        args: [ --fix=lf ]
      - id: check-shebang-scripts-are-executable
  - repo: https://github.com/pocc/pre-commit-hooks # cpp code
    rev: "v1.3.4"
    hooks:
      - id: clang-format
        args: [ --style=Google ]
      - id: clang-tidy
      - id: include-what-you-use
  - repo: https://github.com/ambv/black # python formatting
    rev: "21.10b0"
    hooks:
      - id: black
        language_version: python3.8
        args: [ "--line-length", "120" ]
  - repo: https://github.com/pycqa/flake8 # python pep check
    rev: "4.0.1"
    hooks:
      - id: flake8
        exclude: Docs
        args:
          - "--max-line-length=120"
          - "--ignore=W291,W503,W504"
  - repo: local
    hooks:
      - id: build
        name: build
        entry: /bin/bash scripts/build_ros.sh
        language: script
        pass_filenames: false
        always_run: true
        types: []
        stages: [ "commit", "manual" ]
      - id: cleanup-build
        name: cleanup-build
        entry: /bin/bash scripts/build_ros.sh --clean --no-build
        language: script
        pass_filenames: false
        always_run: true
        verbose: true
        types: []
        stages: [ "post-checkout" ]
